# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field', '0005_auto_20180123_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=40)),
                ('ilce', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldorder', to='field.Field'),
        ),
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='field.Field'),
        ),
        migrations.AlterField(
            model_name='sepet',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='field.Field'),
        ),
    ]
