# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0006_auto_20180124_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='lastName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldorder', to='field.Field'),
        ),
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='field.Field'),
        ),
        migrations.AlterField(
            model_name='sepet',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='field.Field'),
        ),
    ]
