# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0007_auto_20180124_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addressOrder', to='field.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='desc',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldorder', to='field.Field'),
        ),
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='field.Field'),
        ),
        migrations.AlterField(
            model_name='sepet',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='field.Field'),
        ),
    ]
